# Generated by Django 4.1 on 2024-10-04 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=250, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
