# Generated by Django 4.1 on 2024-10-04 09:09

from django.db import migrations, models
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.FileField(null=True, upload_to=first_app.models.user_directory_path),
        ),
    ]
