# Generated by Django 4.1 on 2024-10-04 13:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_cnic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250, null=True)),
                ('tech', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('assigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.person')),
            ],
        ),
    ]
