# Generated by Django 4.1 on 2024-10-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_vehicle_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('roll_no', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='assigne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='first_app.person'),
        ),
    ]
